path: C:\Users\Sager\Desktop\Sager\OHTL Data InsPLAD\InsPLAD-det
train: images/train
val: images/val

nc: 18
names: ['yoke', 'yoke suspension', 'spacer', 'stockbridge damper', 'lightning rod shackle', 'lightning rod suspension', 'polymer insulator', 'glass insulator', 'tower id plate', 'vari-grip', 'polymer insulator lower shackle', 'polymer insulator upper shackle', 'polymer insulator tower shackle', 'glass insulator big shackle', 'glass insulator small shackle', 'glass insulator tower shackle', 'spiral damper', 'sphere']